# Generated by Django 5.2.15 on 2026-06-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('bsc', 'Bachelor of Science (BSc)'), ('btech', 'Bachelor of Technology (BTech)'), ('ba', 'Bachelor of Arts (BA)'), ('bcom', 'Bachelor of Commerce (BCom)'), ('msc', 'Master of Science (MSc)'), ('mtech', 'Master of Technology (MTech)'), ('ma', 'Master of Arts (MA)'), ('phd', 'Doctor of Philosophy (PhD)')], default='bsc', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='thesis_topic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('lab', 'Lab Work'), ('thesis', 'Thesis Evaluation'), ('research_paper', 'Research Paper'), ('presentation', 'Presentation')], default='midterm', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated')], default='active', max_length=15),
        ),
    ]
