# Generated by Django 5.2.14 on 2026-05-30 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('performance', 'Performance Prediction'), ('at_risk', 'At-Risk Detection'), ('dropout', 'Dropout Prediction')], max_length=20)),
                ('predicted_value', models.FloatField()),
                ('confidence', models.FloatField(help_text='Confidence score 0-1')),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
